### ISSUE TITLE
This project seems to have disappeared from the website and been replaced by a template

### ISSUE THREAD

**Issue by JamesHDavenport** [OWASP/www-project-mobile-top-10#1]

**Comment by WillChilcutt** [comment]
Hey James, glad to be not the only one having this issue. I can still see -some of the OWASP Mobile content if you go to https://www.owasp.org/index.php/Projects/OWASP_Mobile_Security_Project_-_Top_Ten_Mobile_Risks . Clicking on most links on that page, however, drops you at the empty template page you're mentioning.

**Comment by WillChilcutt** [comment]
More discussion: https://github.com/OWASP/www-project-mobile-security/issues/14

**Comment by JamesHDavenport** [comment]
Indeed. I’ve been using Wayback to get the old copies for student use.
James

Sent from my iPhone

On 1 Feb 2020, at 22:47, Will <notifications@github.com> wrote:

﻿

Hey James, glad to be not the only one having this issue. I can still see -some of the OWASP Mobile content if you go to https://www.owasp.org/index.php/Projects/OWASP_Mobile_Security_Project_-_Top_Ten_Mobile_Risks . Clicking on most links on that page, however, drops you at the empty template page you're mentioning.

**Comment by JamesHDavenport** [comment]
Thanks – filed an issue asking for a link to the archive.

**Comment by WillChilcutt** [comment]
Hey @JamesHDavenport I created a PR pulling over a lot of the content so that if someone is searching they can find the content in it's new spot: https://github.com/OWASP/www-project-mobile-top-10/pull/2

It's a work in progress, but at least a start. People are still searching and ending up empty-handed (like I was originally just getting into the project last month) so I think it'll be valuable to get -something- up for now.

Thanks!

**Comment by WillChilcutt** [comment]
Hey @JamesHDavenport I think we knocked this one out! Let me know if there is more you or your students are missing.

**Comment by JamesHDavenport** [comment]
Many thanks.  They have a choice between original OWASP, Mobile and API.  In mobile, two groups have chosen M5 and M8.
I‘ll let you know how they get on.
